### ISSUE TITLE
少年你的博客好像挂了

### ISSUE THREAD

**Issue by MichaelLynx** [maoruibin/maoruibin.github.com#96]
打不开了

**Comment by maoruibin** [comment]
> 打不开了

早晨还提交了几次更改呢，我检查一下，多谢提醒...

**Comment by MichaelLynx** [comment]
> > 打不开了
> 
> 早晨还提交了几次更改呢，我检查一下，多谢提醒...

想上去看一下，发现打不开了。然后我的好像也打不开了。。。应该是github的原因，翻了就能上了。。。。。

**Comment by MichaelLynx** [comment]
希望是临时的。。。

**Comment by maoruibin** [comment]
> 希望是临时的。。。

貌似找到问题了，是评论组件的问题。我看所有使用同样评论组件的网站好像都打不开

**Comment by MichaelLynx** [comment]
valine吗，打开了一个disqus的好像是正常的，其他的没办法看也不知道是什么情况。

**Comment by MichaelLynx** [comment]
看来就昨天被临时封锁了，今天已经恢复正常了。也许平时也有这样，只是今天才被注意到吧。。。

**Comment by maoruibin** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    可能，我昨天还把 Valine 给下了 
    
    
    

    

    

    在2020年03月27日 10:05，Lynx<notifications@github.com> 写道： 




看来就昨天被临时封锁了，今天已经恢复正常了。也许平时也有这样，只是今天才被注意到吧。。。

**Comment by MichaelLynx** [comment]
让子弹先飞一会儿，哈哈

**Comment by MichaelLynx** [comment]
https://www.oschina.net/news/114402/git-mitm，被黑客攻击了

**Comment by maoruibin** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    嗯嗯，今天看到新闻了 ~  
    
        
            
        
    
    
    
    

    

    

    在2020年03月27日 11:05，Lynx<notifications@github.com> 写道： 




https://www.oschina.net/news/114402/git-mitm，被黑客攻击了

**Comment by maoruibin** [comment]
![test](https://oss.payjs.cn/5eb21a0a53b7b)
